ato_opt_histogram : ato_opt_histogram.cpp ato_opt_histogram.cl
	g++ ato_opt_histogram.cpp -o ato_opt_histogram -I/opt/AMDAPPSDK-3.0/include /opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so
clean:
	rm ato_opt_histogram
